### ISSUE TITLE
sounds

### ISSUE THREAD

**Issue by frankalison** [Ratismal/DiscordMungeon#2]
Instead of playing the sound at the time of the attack, it would be best if you touched it when you were ready to attack it or sound when you were ready to gather.
And options to disable each one

**Comment by Ratismal** [comment]
why am i the only one on point

**Comment by Ratismal** [comment]
i understand where you're coming from in terms of notification, but it makes more semantic sense for a fanfare to play as you attack. i'll keep this in mind for future updates though.
